version: "3.9"

services:
  renting-api:
    container_name: rentingprototype
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./src/RentingPrototype.Host/data/schema:/app/data/schema:ro
      - ./logs:/app/logs
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
