<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RentingPrototype.Application\RentingPrototype.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Endpoints/Rental/" />
    <Folder Include="Endpoints/RentalHistory/" />
    <Folder Include="Endpoints/Vehicle/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>cddc6e5b-365f-4a20-8493-18f4876c3aee</UserSecretsId>
  </PropertyGroup>

</Project>
