<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RentingPrototype.Application\RentingPrototype.Application.csproj" />
    <ProjectReference Include="..\RentingPrototype.Infrastructure\RentingPrototype.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
  <Content Include="..\RentingPrototype.Infrastructure\Persistence\Schema\rentingprototype-schema.sql">
    <Link>rentingprototype-schema.sql</Link>
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
</ItemGroup>

  <ItemGroup>
    <Folder Include="Endpoints/Rental/" />
    <Folder Include="Endpoints/RentalHistory/" />
    <Folder Include="Endpoints/Vehicle/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.12.53" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>cddc6e5b-365f-4a20-8493-18f4876c3aee</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfilePath>..\..\Dockerfile</DockerfilePath>
    <ContainerBuildContext>$(MSBuildThisFileDirectory)..\..</ContainerBuildContext>
  </PropertyGroup>

</Project>
