<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RentingPrototype.Domain\RentingPrototype.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions/" />
    <Folder Include="RentalHistory/Interfaces/" />
    <Folder Include="RentalHistory/Queries/CustomerRentalHistory/" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
